apiVersion: velero.io/v1
kind: Restore
metadata:
  name: new-cluster-1
  namespace: velero
spec:
  backupName: old-cluster-1
  includedNamespaces:
  - '*'
  includedResources:
  - persistentvolumeclaims
  - persistentvolumes
  namespaceMapping:
    default: systems
    pv: infra
