apiVersion: velero.io/v1
kind: Restore
metadata:
  name: argo-18-7-23-7.54am
  namespace: velero
spec:
  backupName: argo-18-7-23-7.05am
  includedNamespaces:
  - '*'
  includedResources:
  - persistentvolumeclaims
  - persistentvolumes
  namespaceMapping:
    default: systems
    pv: infra
